### ISSUE TITLE
change for home

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#1]
Looking to get work within the Private Security Industry, such as Door Supervision, Security Guarding or CCTV Operator, working in shops, factories, clubs, events etc? Then look no further for your course & qualification in order to apply for an SIA licence. EZ Training is a local company, based in Newtownabbey, Northern Ireland.

**Comment by itsmat32143** [comment]
No problem ill get that sorted for you @DEEHP4 any other issues just log them and I will get them sorted asap 👍

**Comment by itsmat32143** [comment]
Issue Resolved 07/12/2020 20:12
