### ISSUE TITLE
Snippet / Metatag tweak

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#10]
Hi Matthew,
Are you able to amend the snippet / Metatag showing under my site search?

**It's currently showing:**  
SIA courses in BELFAST | Door Supervisor, CCTV,
Door Supervisor only £195. CCTV £175. Security Guard Training £175. Courses: Door Supervision course, CCTV course, SIA Training Courses

**If it could possibly changed, with no costs showing, as follows:**
SIA courses in BELFAST | Door Supervisor, CCTV,
Door Supervision + First-Aid option, CCTV (Public Space Surveillance). Security Guarding. SIA Training Courses

Any queries please get in touch.
Thanks, Dee

**Comment by itsmat32143** [comment]
No problem just out of work will get this sorted when home 👍👍👍

**Comment by DEEHP4** [comment]
Thanks mate.  I hope your work is going well.

I remember creating these in Wordpress ages ago, but now that it's via Github I assumed you'd be able to amend this.  I imagine it will then need re-submitted to Google - for the change to gradually take effect?

Cheers,
Dee

**Comment by itsmat32143** [comment]
Yeah i can change them and update them with Google and bing 👍👍

**Comment by DEEHP4** [comment]
Brilliant mate, Thank you!!

**Comment by itsmat32143** [comment]
All changes done don't know how long it takes Google and bing to update so i will leave this issue open till Google and bing update it 👍👍

**Comment by DEEHP4** [comment]
You're a star Matthew, Thank you!!

**Comment by itsmat32143** [comment]
![Screenshot_20210216-122556.png](https://user-images.githubusercontent.com/44469185/108062945-6b9ccf00-7052-11eb-912b-c9719f263568.png)

Google has updated bing hasn't updated yet 👍

**Comment by itsmat32143** [comment]
I sent a request to access the google ads to change them 👍👍👍

**Comment by DEEHP4** [comment]
That should be done Matthew.  Let me know if there's any problems.

Cheers! 
 
 
 
 
-------Original Message-------
 
From: Matty
Date: 02/18/21 18:23:32
To: NIWebDesigns/SIA-Training-Website
Cc: DEEHP4;  Author
Subject: Re: [NIWebDesigns/SIA-Training-Website] Snippet / Metatag tweak
(#10)
 
I sent a request to access the google ads to change them 👍👍👍
