### ISSUE TITLE
Verify Domain Ownership via DNS Record

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#11]
Matthew,
I went into my **Google Webmaster Tools**, and this comes up right away.  Is this something which needs done, or maybe it's already done and I should just ignore it?
 
![DNS Screen Shot 002](https://user-images.githubusercontent.com/75130854/108065919-91c46e00-7056-11eb-8f77-c0856b9b2260.JPG)

**Copy the TXT record below into the DNS configuration for eztraining.co.uk**
google-site-verification=_KStcQbOYlbDUm07Ky7irFMqz3dUwgYfc0lRPrbdojA

**Comment by itsmat32143** [comment]
You need to input that into your domain provider as a txt

**Comment by DEEHP4** [comment]
I'm sure I done this years ago.  I'll try to redo it in case required.

Many Thanks

**Comment by itsmat32143** [comment]
It may have been removed when switching over to GitHub

**Comment by DEEHP4** [comment]
Of course. Now added
![NamesCo TXT](https://user-images.githubusercontent.com/75130854/108067491-c5a09300-7058-11eb-94a9-c133b44ef662.JPG)

Cheers!

**Comment by itsmat32143** [comment]
If you go back and click verify it should sort it 👍

**Comment by DEEHP4** [comment]
Yes, sorry, I should have said that I also clicked on verify and it was acknowledged straight after.
