### ISSUE TITLE
Metatag / Snippet

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#12]
Matthew,
Regarding the metatag info:  As well as the prices just being removed, it might be good to have something like this **if possible**:

**SIA courses. Door Supervision, First-Aid, CCTV, Security Guarding, SIA `Top-Up` Refresher**

Happy to discuss,
Dee

**Comment by itsmat32143** [comment]
So have this as the metatag not what's in the other issue ???

**Comment by itsmat32143** [comment]
also, that google request I sent to sort the ads says you haven't accepted?

**Comment by DEEHP4** [comment]
Clicking on `Add` does nothing, except a little blink.  I'll try to amend the Ads then.

The text you recently amended shows: SIA courses in BELFAST | Door Supervisor, CCTV, Door Supervision + First-Aid option, CCTV (Public Space Surveillance). Security Guarding.

The Google Ads metatag shows: SIA courses in Northern Ireland. Door Supervision £195; CCTV £175; Security Guarding £175. Looking to get the qualification in order to apply for an SIA licence? Step-By-Step Instructions. Local Company. HABC Registered. Courses: Door Supervisor +FirstAid, CCTV.

I thought it might actually be best to have it as:  **SIA courses. Door Supervision, First-Aid, CCTV, Security Guarding, SIA Top-Up Refresher**  as it could help highlight first-aid on its own as well as the Refresher.  Over the coming months people will start searching for SIA Top Up, SIA Refresher...

**Comment by DEEHP4** [comment]
Regarding incognito tab, I wouldn't even know how to do this.

I went into the Ads & Extensions, selected `Structured Snippet`, clicked on `Add New`, inserted the new text and clicked on `Save`.  It looks fine, but then when I scroll down the (old?) snippet preview still shows the old prices.

Unless the new snippet will gradually replace the old - once Google approves it???

![New updated snippet](https://user-images.githubusercontent.com/75130854/108433038-3b655400-723d-11eb-92d4-b4a8fa3ccc0c.JPG)
![Structured snippet still showing prices](https://user-images.githubusercontent.com/75130854/108433041-3bfdea80-723d-11eb-9eaf-2c913229f142.JPG)

**Comment by DEEHP4** [comment]
Even though I clicked on Add New and pasted the text in: **SIA courses: Door Supervision, First-Aid, CCTV, Security Guarding, SIA Top-Up Refresher** it still keeps the old text with prices

**Comment by DEEHP4** [comment]
I've also disabled the Google **Automated Snippets** - to see if it eventually gets rid of the old greyed-out text/prices.

![Automated Snippets](https://user-images.githubusercontent.com/75130854/108434281-4faa5080-723f-11eb-80e4-06109f2d909a.JPG)

**Comment by DEEHP4** [comment]
I just tried following this guy's info:  https://www.youtube.com/watch?v=xN6RbCh4SLI

**Comment by DEEHP4** [comment]
Matthew,
It would be good if the snippet/tag continues to show the part in bold **SIA courses in BELFAST** (with the new text afterwards).  I appreciate this is what you're doing anyhow.

Cheers!
Dee

![Google Ad view](https://user-images.githubusercontent.com/75130854/108552942-e9c6d300-72e9-11eb-80e3-168bdb60aad8.JPG)

**Comment by DEEHP4** [comment]
Actually I don't mind if the **SIA courses in Northern Ireland** also remains underneath, as shown in the screenshot.

**Comment by itsmat32143** [comment]
👍

**Comment by itsmat32143** [comment]
AD - Looking to get the qualification in order to apply for an SIA licence? We can help. Courses: Door Supervision, CCTV, First-Aid, Security Guarding, 3 Year Top-Up Refresher.

Google Website - SIA courses in BELFAST | Door Supervisor, CCTV, Door Supervision + First-Aid option, CCTV (Public Space Surveillance). Security Guarding. SIA Training ...

Bing Website - SIA licence training made EZ Looking to get work within the Private Security Industry, such as Door Supervision, Security Guarding or CCTV Operator, working in shops, factories, clubs, events etc? Then look no further EZ Training is a local company, based in Newtownabbey, Northern Ireland.

Are you happy with this or what do you want them changed to?

**Comment by DEEHP4** [comment]
Ok mate,If possible:Ideally all Websites/ browsers, but mostly Google:     SIA courses in BELFAST | Door Supervisor, CCTV, First-Aid, Security Guarding, 3 year Top-Up Refresher.Or if there's enough space:SIA courses in BELFAST | Door Supervisor, CCTV (Public Space Surveillance), First-Aid, Security Guarding, 3 year Top-Up Refresher.ThanksSent from my Galaxy
-------- Original message --------From: Matty <notifications@github.com> Date: 20/02/2021  20:20  (GMT+00:00) To: NIWebDesigns/SIA-Training-Website <SIA-Training-Website@noreply.github.com> Cc: DEEHP4 <d.mallon99@virginmedia.com>, Author <author@noreply.github.com> Subject: Re: [NIWebDesigns/SIA-Training-Website] Metatag / Snippet (#12) 
AD - Looking to get the qualification in order to apply for an SIA licence? We can help. Courses: Door Supervision, CCTV, First-Aid, Security Guarding, 3 Year Top-Up Refresher.
Google Website - SIA courses in BELFAST | Door Supervisor, CCTV, Door Supervision + First-Aid option, CCTV (Public Space Surveillance). Security Guarding. SIA Training ...
Bing Website - SIA licence training made EZ Looking to get work within the Private Security Industry, such as Door Supervision, Security Guarding or CCTV Operator, working in shops, factories, clubs, events etc? Then look no further EZ Training is a local company, based in Newtownabbey, Northern Ireland.
Are you happy with this or what do you want them changed to?

**Comment by itsmat32143** [comment]
Google Ads and Bing Ads I can't get access to probably because you pay for them so only you can have access I have changed the Google and Bing Metadata to the long one that you wanted that should update soon 👍👍 You also have a web app now too that I added in 👍👍 Idk if you can add me into the google ads or if you can only do it yourself but let me know

Thanks 
Matthew

**Comment by DEEHP4** [comment]
Ok mate, Thank you!!Lets see it it looks over the coming days. The biggest priority is the prices disappearing. I'm not too fussed if the text is repeated in the metatag, or if short or long. As long as it hopefully somehow shows the Door Supervision, CCTV, First-Aid, Security Guarding, 3 year Top-Up Refresher.  (Or close to it).Many ThanksSent from my Galaxy
-------- Original message --------From: Matty <notifications@github.com> Date: 21/02/2021  15:51  (GMT+00:00) To: NIWebDesigns/SIA-Training-Website <SIA-Training-Website@noreply.github.com> Cc: DEEHP4 <d.mallon99@virginmedia.com>, Author <author@noreply.github.com> Subject: Re: [NIWebDesigns/SIA-Training-Website] Metatag / Snippet (#12) 

Google Ads and Bing Ads I can't get access to probably because you pay for them so only you can have access I have changed the Google and Bing Metadata to the long one that you wanted that should update soon 👍👍 You also have a web app now too that I added in 👍👍 Idk if you can add me into the google ads or if you can only do it yourself but let me know

Thanks

Matthew

**Comment by DEEHP4** [comment]
The App is a great wee touch Matthew, Thanks!Sent from my Galaxy
-------- Original message --------From: Matty <notifications@github.com> Date: 21/02/2021  15:51  (GMT+00:00) To: NIWebDesigns/SIA-Training-Website <SIA-Training-Website@noreply.github.com> Cc: DEEHP4 <d.mallon99@virginmedia.com>, Author <author@noreply.github.com> Subject: Re: [NIWebDesigns/SIA-Training-Website] Metatag / Snippet (#12) 

Google Ads and Bing Ads I can't get access to probably because you pay for them so only you can have access I have changed the Google and Bing Metadata to the long one that you wanted that should update soon 👍👍 You also have a web app now too that I added in 👍👍 Idk if you can add me into the google ads or if you can only do it yourself but let me know

Thanks

Matthew

**Comment by itsmat32143** [comment]
Not a problem 👍👍
