### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#2]
**Matty,
One of the paragraphs in `About us` just to be tweaked to show:** 
We are a local company based in Newtownabbey, Northern Ireland, taking pride in our work in order to deliver the key knowledge &amp; skills to help people get through their course successfully, as well as gain the necessary qualities to work within the Private Security Industry and hopefully excel.  During the course, candidates are provided with some employment advice and a list of some of the key security providers in Northern Ireland, which includes some whom are frequently seeking to recruit new security staff.

**Comment by itsmat32143** [comment]
No problem will get that sorted too @DEEHP4

**Comment by itsmat32143** [comment]
Issue Resolved 07/12/2020 20:16
