### ISSUE TITLE
Slight change to FAQ answer

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#4]
Hi Matty,
Regarding the question: What if I (or a group booked by an organisation) suddenly.....?  (as attached):

It currently seems to have `course` mentioned too much. Can you please replace the answer with this tweaked version:

If you notify EZ Training early enough, i.e. 7 working days notice, we will book you on to a later available course. If however, you fail to notify us in advance or just don’t turn up on the morning of the course, then you will lose your fee, as besides registration, order of your exams and book, this will have also affected someone else trying to book a place. For a company group (or individual/s) which do not arrive for the course, the same applies as detailed above, which has also affected the day/s booked and registered being wasted, when another course for other paying applicants could have been arranged and filled for the same dates. 

Many Thanks,
Dee
![Original text](https://user-images.githubusercontent.com/75130854/101983659-5f704c00-3c74-11eb-8a62-d361dba6292f.JPG)

**Comment by itsmat32143** [comment]
Yes not a problem dee I will get that sorted now for you 👍

**Comment by itsmat32143** [comment]
Issue Resolved 12/12/2020 21:28
