### ISSUE TITLE
Addition to website

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#5]
Hi Matty,
I hope you and your family are keeping well.

As you may be aware, the SIA are going ahead **from the 1st April 2021** with the new requirements for anyone doing a Door Supervision (or Security Guarding) course for the first time, where they must have a First Aid qualification before they start the SIA course.

Then from October 2021, anyone renewing their licence must have First-Aid and a Refresher on certain aspects of the course (to include Physical Intervention).  All the details are shown on this SIA link anyhow: https://www.gov.uk/government/news/changes-to-the-training-you-need-for-an-sia-licence

Due to these upcoming changes, can you please add in other options for me into the website, as follows:

1.  _Under the `BOOK NOW` tab menus, can you add in (as the first option on the left):_ Emergency First-Aid at Work + Door Supervision **£265**   6 Days (Mon-Sat) _with the text underneath showing:_  SIA requirement from 1st April 2021 to have First-Aid.  This course also allows you to work in all Security Guard roles.

2.   _Under the `BOOK NOW` tab menus, can you add in (as the second option from the left):_ **Door Supervision **£195**  5 Days (Mon-Fri)  _with the text underneath showing:_  For those who have an existing VALID First-Aid qualification / certificate.  This course also allows you to work in all Security Guard roles.

3.  _Under the `BOOK NOW` tab menus, can you add in (as the third option from the left):_ **Emergency First-Aid at Work + Security Guarding **£245** 4 Days (Mon-Thu)  _with the text underneath showing:_  SIA requirement from 1st April 2021 to have First-Aid. For basic Security Guarding only. 

3.  _Under the `BOOK NOW` tab menus, can you add in (as the last on the right, even replacing `Conflict Management`):_  **`Top-Up` Qualification + First-Aid for Door Supervisors and Security Guards from 1st October 2021.  3 Days (Mon-Wed) **£145**  Dates to be arranged.

_In the FAQ section (under `General`) can you please add:_

1.  **Can I just do the Door Supervision (or Security Guarding) course without doing the First-Aid?**
Only if you have an existing valid First-Aid qualification and can produce the original certificate (for us to check and photocopy on the first morning of your security course).  This can include: First Aid at Work (FAW);  First Person on Scene (FPOS);  First Response Emergency Care (FREC). Further details can be found via this link: https://www.gov.uk/government/news/changes-to-the-training-you-need-for-an-sia-licence

2.  **I have tried renewing my SIA licence, but have been informed by the SIA that I am required to do `Top-Up` training.  Can you advise?**
The SIA have been considering this for a while, which is now being introduced from 1st October 2021. Just like a some other training courses, including First-Aid, the Door Supervision and Security Guarding roles now require a `Refresher` in certain modules, such as Physical Intervention theory & practical, Counter-Terrorism, Suspicious Behaviour, Vulnerable People, etc. and First-Aid (if not already achieved or currently valid).  Some details can be found via this link:  https://www.gov.uk/government/news/changes-to-the-training-you-need-for-an-sia-licence

3.  **I have already completed my Door Supervision (or Security Guarding) course within the last 3 years.  Am I required to do the new course with First-Aid?** 
No, providing you apply for your SIA licence BEFORE 1st October 2021, i.e. possibly by August 2021, to allow enough time for the processing of your licence.  Further details are shown in this link: https://www.gov.uk/government/news/changes-to-the-training-you-need-for-an-sia-licence

I hope this all makes sense Matty, but please don't hesitate to give me a call (day or night).  As before, we can make any tweaks if required.

Many Thanks,
Dee

**Comment by itsmat32143** [comment]
Not a problem will get this sorted asap 👍

**Comment by itsmat32143** [comment]
Issue Resolved 08/02/2021 18:35
