### ISSUE TITLE
CCTV option missing

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#6]
Sorry Matthew,  
Can you please re-insert the original **CCTV** option 4 days (Mon-Thu)  £175.00         

I must have forgot to ask you to keep that in the options. 

Many Thanks!  
Dee

**Comment by itsmat32143** [comment]
Not a problem

**Comment by DEEHP4** [comment]
Can you please also amend the basic Door Supervision to show 5 Days (Tue-Sat).   NOT the existing Mon-Fri.

Apologies mate

**Comment by itsmat32143** [comment]
What do you want under CCTV??

**Comment by itsmat32143** [comment]
Issue Resolved 08/02/2021 20:10
