### ISSUE TITLE
Menus, including `Top-Up` option

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#7]
The CCTV looks good mate, including the text under.

As you may be aware though, the options seem to be squashed down a bit - due to the main menu across the top.

Also, I think it may be best for the Top Up to be changed to **3 Year `Top-Up` Refresher** if you could please tweak that, as well as the cost to £135 (which might possibly change again months later). 

Thank you!

**Comment by DEEHP4** [comment]
Matthew,
Great job with the FAQ section too.  Fussy I know, but under the FAQ question "I have tried renewing my SIA licence...."  can you please remove the letter `a` from the start of the answer: Just like **a** some other training courses, including First-Aid..

Thanks!!

**Comment by itsmat32143** [comment]
is the pricing page all okay now?

**Comment by DEEHP4** [comment]
Sorry for the hassle mate.  If the CCTV could show: **CCTV _(Public Space Surveillance)_**

**Comment by itsmat32143** [comment]
NP everything else is sorted

**Comment by DEEHP4** [comment]
Yes mate, perfect, Thank you!!!   How do I send you a few quid?

**Comment by itsmat32143** [comment]
Don't worry about it 👍

**Comment by itsmat32143** [comment]
CCTV Name Updated too👍

**Comment by DEEHP4** [comment]
Smashing job mate.  I really appreciate the prompt changes and your great patience.  I owe you

**Comment by itsmat32143** [comment]
Not a problem any more just let me know 👍

**Comment by itsmat32143** [comment]
Issue Resolved 08/02/2021 20:37
