### ISSUE TITLE
Course options & prices

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/SIA-Training-Website#8]
Hi Matthew,
The SIA have now confirmed their new changes and requirements, which is even more demand than anticipated.

Due to more days added, bigger exams, costs etc, can you please make the following tweaks to the course options:

- **Option 1** (First Aid + DS): Cost to be changed to **£285**.   If you could please also remove the 6 Days (Mon-Sat), as I'm able to add these in with the PayPal menu, which will now be 7 Days.

- **Option 2** (CCTV) can just remain the same for now, although cost will increase from 1st April.  **Please remove the 4 Days (Mon-Thu).**  Once dates are confirmed I will let you know, then the cost can show £195.  

- **Option 3** (DS only): Cost to be changed to **£225**    Text to show: For those who have an existing VALID First-Aid qualification / certificate **with at least 12 months remaining**. This course also allows you to work in all Security Guard roles.                                                   **Please also remove the 5 Days (Tue-Sat)**  

- **Option 4** (First Aid + SG):  Cost to be changed to **£265**     **Please also remove the 4 Days (Mon-Thu)**   

- **Option 5** (Top-Up Refresher):  **Please just remove the 3 Days (Mon-Wed)**  

FAQ (General) section:
**Can I just do the Door Supervision (or Security Guarding( course without doing the First-Aid?**
The SIA state: Only if you have an existing valid First-Aid qualification **with at least 12 months remaining**, and can produce the original certificate (for us to check and photocopy on the first morning of your security course). This can include: First Aid at Work (FAW); First Person on Scene (FPOS); First Response Emergency Care (FREC). Further details can be found via this link: https://www.gov.uk/government/news/changes-to-the-training-you-need-for-an-sia-licence

**English isn't my first language language.  Will this matter?**
It is a requirement that you have an acceptable level of English Speaking, Listening, Reading and Writing.  Not just for understanding all the subjects covered and the various multiple-choice exams involved during the course, but to also work within the Private Security Industry, possibly dealing with people, incidents (& reports) and Emergency Services, etc.  Please get in touch if you have any queries or concerns about this.

That should be all for now Matthew, and please do hesitate to call me, even if later in the night.

Many Thanks,
Dee

**Comment by itsmat32143** [comment]
Not a problem will get this all sorted asap either tonight or tomorrow morning 👍👍👍

**Comment by DEEHP4** [comment]
No big rush at all mate.Thank you!Sent from my Galaxy
-------- Original message --------From: Matty <notifications@github.com> Date: 11/02/2021  22:33  (GMT+00:00) To: NIWebDesigns/SIA-Training-Website <SIA-Training-Website@noreply.github.com> Cc: DEEHP4 <d.mallon99@virginmedia.com>, Author <author@noreply.github.com> Subject: Re: [NIWebDesigns/SIA-Training-Website] Course options & prices (#8) 

Not a problem will get this all sorted asap either tonight or tomorrow morning 👍👍👍

**Comment by itsmat32143** [comment]
Are you sure you want the days removed I don't mind updating them if they change I just think they look a bit better split off from the PayPal totally up to yourself

**Comment by DEEHP4** [comment]
I agree, it does look a bit better mate, but there may be sudden times when
I have to change the days, for example Mon-Thu,  to  Tue-Fri,  or possibly
have to add or subtract a day due to the way the SIA and Awarding Bodies
sometimes dictate different things.


 
 
 
 
-------Original Message-------
 
From: Matty
Date: 12/02/2021 01:01:23
To: NIWebDesigns/SIA-Training-Website
Cc: DEEHP4;  Author
Subject: Re: [NIWebDesigns/SIA-Training-Website] Course options & prices
(#8)
 
Are you sure you want the days removed I don't mind updating them if they
change I just think they look a bit better split off from the PayPal totally
up to yourself

**Comment by itsmat32143** [comment]
I think that is everything sorted that you said have a look and let me know what you think 👍

**Comment by DEEHP4** [comment]
Great job Matthew, Thank you very much.I hope you're getting on ok with work and in general.I'll be in touch if any other tweaks are needed down the line. Cheers mate!DeeSent from my Galaxy
-------- Original message --------From: Matty <notifications@github.com> Date: 12/02/2021  02:35  (GMT+00:00) To: NIWebDesigns/SIA-Training-Website <SIA-Training-Website@noreply.github.com> Cc: DEEHP4 <d.mallon99@virginmedia.com>, Author <author@noreply.github.com> Subject: Re: [NIWebDesigns/SIA-Training-Website] Course options & prices (#8) 

I think that is everything sorted that you said have a look and let me know what you think 👍
